# -*- coding: utf-8 -*-
"""The gate spine, activity by activity.

Each entry is a list of gates in the order they appear down the page:
  ('tick', section_id, gate_id, label, kicker, sentence)
  ('ask',  section_id, gate_id, label)          -- text comes from CHECKS
  ('typer', None, gate_id, label)               -- wraps the type-it-here box
  ('quiz',  None, 'quiz', 'Quiz')
"""

GATES = {
0: [
 ('ask','language','lang','What MicroPython is'),
 ('ask','errors','err','Reading an error'),
 ('tick','checklist','wokwi','Wokwi ready','Checkpoint &mdash; Wokwi is ready',
  'A new <strong>Pico + MicroPython</strong> project opens, and my five-line program is printing in the Serial Monitor.'),
 ('tick','checklist','thonny','Board ready','Checkpoint &mdash; the real board is ready',
  'Thonny is installed, the bottom-right corner says <strong>MicroPython (Raspberry Pi Pico)</strong>, and the same program runs from <code>main.py</code>.'),
 ('tick','trythis','fix','Break it and mend it','Checkpoint &mdash; I can break it and mend it',
  'I changed the message and the speed, then broke the program on purpose and put it back together.'),
 ('quiz',None,'quiz','Quiz'),
],
1: [
 ('ask','pins','pins','Why the pin number matters'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'Wokwi: the LED&rsquo;s long leg goes through the 330&nbsp;&Omega; resistor to <span class="gp">11</span>, and the short leg to GND. Real board: the power light is on and the Shell shows <code>&gt;&gt;&gt;</code>.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'The red LED is glowing and <em>stays</em> glowing. The yellow and green stay dark, and nothing is beeping.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'All three LEDs are on at once, and they stay on.'),
 ('quiz',None,'quiz','Quiz'),
],
2: [
 ('ask','idea','idea','Why it has to wait'),
 ('ask','indent','indent','What the spaces mean'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'Nothing new to wire &mdash; the LED and resistor from Activity 1 are still on <span class="gp">11</span> and GND, with no warning triangle on the part.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'The red LED goes on and off <em>by itself</em>, about once a second, and keeps going until I stop it on purpose.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'Traffic light: the three colours take turns in the right order, only one is lit at a time, and the yellow is clearly the shortest.'),
 ('quiz',None,'quiz','Quiz'),
],
3: [
 ('ask','pwm','pwm','How the arm is told where to go'),
 ('ask','pin','pin','Three names, one hole'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'The servo&rsquo;s three wires are in: signal to the pin my route&rsquo;s table gives, red to power, brown or black to GND. Wokwi and the LilEx5 use <strong>different</strong> numbers &mdash; I used the ones for my route.'),
 ('tick','code','code','Program typed','Checkpoint &mdash; typed, not pasted',
  'I typed the program myself, into Wokwi or Thonny. Every character of it.'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'The arm swings to left, middle and right, waits long enough at each one to see it, and the Shell says where it is going.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'My signal arm moves to the position the program asks for, holds there long enough to read, and keeps its cycle going.'),
 ('quiz',None,'quiz','Quiz'),
],
4: [
 ('ask','idea','idea','Out, and in'),
 ('ask','trap','trap','The backwards number'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'Wokwi: one leg of the pushbutton goes to <span class="gp">2</span> and the leg <strong>diagonally opposite</strong> goes to GND. Real board: the Shell shows <code>&gt;&gt;&gt;</code> and I know which of the three buttons is SW1.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'Numbers are appearing on their own: <strong>1</strong> when I am not touching the button, <strong>0</strong> while I hold it down, and 1 again when I let go.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'Both buttons print on the same line, each with its own label, and each one changes only its own number.'),
 ('quiz',None,'quiz','Quiz'),
],
5: [
 ('ask','idea','idea','What else adds'),
 ('ask','trap','trap','One equals sign, or two'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'A pushbutton <em>and</em> an LED this time: button leg to <span class="gp">2</span> with the opposite leg to GND, LED long leg through the resistor to <span class="gp">11</span> with the short leg to GND.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'The light is off when nobody is touching the button, comes on while I hold SW1 down, and goes out the moment I let go.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'SW1 lights the red LED, SW2 lights the green one, both together light both &mdash; and everything goes out when I let go.'),
 ('quiz',None,'quiz','Quiz'),
],
6: [
 ('ask','tables','tables','The strictest word'),
 ('ask','whole','whole','Each half is a whole question'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'Two pushbuttons this time &mdash; SW1 to <span class="gp">2</span>, SW2 to <span class="gp">3</span>, each with its diagonally opposite leg to GND &mdash; plus the LED on <span class="gp">11</span>.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'Holding one button on its own does <em>nothing at all</em>. Holding both lights the red LED, and letting go of either one puts it straight out.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'Two-key safe: one key alone never opens it, and any two of the three together do.'),
 ('quiz',None,'quiz','Quiz'),
],
7: [
 ('ask','bus','bus','Two wires, many parts'),
 ('ask','library','lib','What a library is'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'Four wires to the screen: SDA to <span class="gp">0</span>, SCL to <span class="gp">1</span>, GND to a ground pin and VCC to 3V3. And <code>ssd1306.py</code> is on the Pico, not just on my computer.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'Words appeared on the <em>screen</em>, both lines, with a clear gap between them &mdash; and I changed them to my own name and ran it again.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'Both lines say UP until I press. SW1 changes only the first line, SW2 only the second, and nothing is left over from the round before.'),
 ('quiz',None,'quiz','Quiz'),
],
8: [
 ('ask','numbers','numbers','Why a sensor has a decimal point'),
 ('ask','try','equals','Asking a sensor the wrong question'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'The sensor is on the <em>same</em> two wires as the screen &mdash; SDA to <span class="gp">0</span>, SCL to <span class="gp">1</span> &mdash; plus GND and 3V3, and the screen&rsquo;s four wires are still there and untouched.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'Numbers are scrolling up the Shell and the screen shows a short number under the word Tilt &mdash; and <em>both</em> change as I tilt the board.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'The light comes on when I tilt the board past about halfway and goes out when I set it back down flat, over and over, for as long as I leave it running.'),
 ('quiz',None,'quiz','Quiz'),
],
9: [
 ('ask','adc','adc','What the ADC does'),
 ('ask','probe','probe','Backwards again'),
 ('tick','build','build','Circuit ready','Checkpoint &mdash; the circuit is ready',
  'Three wires: AOUT to <span class="gp">26</span>, VCC to 3V3 and GND to a ground. On the real board it was <strong>switched off while I wired it</strong>, and both prongs are in the soil to the same depth.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'Numbers are scrolling up the Shell, and wetting the soil (or dragging the slider up) makes the raw number go <em>down</em>.'),
 ('tick','calibrate','calibrate','Calibrated','Checkpoint &mdash; calibrated with my own numbers',
  'My own air reading and soaked reading are written down and are <em>in my program</em> &mdash; the worksheet&rsquo;s two numbers are gone. Wet soil now says WET, dry soil says DRY, and the percentage moves sensibly in between.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'The LED warns me that the soil is dry with no screen and no Shell needed.'),
 ('quiz',None,'quiz','Quiz'),
],
10: [
 ('ask','mqtt','mqtt','What sits in the middle'),
 ('ask','account','key','Your key is a password'),
 ('tick','build','build','Ready to send','Checkpoint &mdash; ready to send',
  'My feed exists with an empty chart waiting on a dashboard, the board is on, and I have the name and password of a <strong>2.4&nbsp;GHz</strong> network.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'The Shell says it joined the network and connected to Adafruit IO, a line appears every five seconds, and <strong>points are landing on my dashboard graph</strong>.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'The screen shows Temp with a reading under it, changing as the room changes, while the graph keeps filling up at the same time.'),
 ('quiz',None,'quiz','Quiz'),
],
11: [
 ('ask','turn','turn','Which way round'),
 ('ask','callback','callback','Handing over a function'),
 ('tick','build','build','Ready to listen','Checkpoint &mdash; ready to listen',
  'The red LED is on <span class="gp">11</span> and the green on <span class="gp">13</span>, each through its own resistor; my <code>led</code> feed has a Toggle on a dashboard, and clicking it already puts a new row in the feed.'),
 ('typer',None,'code','Program typed'),
 ('tick','run','run','It works','Checkpoint &mdash; it works',
  'The Shell printed <em>On the network</em> and then <em>Listening</em>. Clicking the switch to ON lights the red LED, OFF puts it out, and a line appears in the Shell for every flip.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'ON lights the red one and puts the green out, OFF does the opposite, and exactly one is lit at any moment &mdash; never both.'),
 ('quiz',None,'quiz','Quiz'),
],
12: [
 ('ask','noserver','noserver','Nobody in the middle'),
 ('ask','mode','mode','The three mode pins'),
 ('tick','kit','kit','Kit ready','Checkpoint &mdash; the kit is ready',
  'My antenna is screwed on &mdash; and so is the antenna of the person next to me &mdash; and Thonny says <strong>Raspberry Pi Pico</strong> in the bottom-right corner.'),
 ('typer',None,'code','Program typed'),
 ('tick','listen','listen','I caught a broadcast','Checkpoint &mdash; I caught a broadcast',
  '<code>listen.py</code> is saved on the Pico, the first line appeared and then the Shell went quiet &mdash; and my instructor&rsquo;s broadcast arrived on my screen.'),
 ('tick','send','send','I answered back','Checkpoint &mdash; I answered back',
  'My own name is in the message, and I went and found it on my instructor&rsquo;s screen.'),
 ('quiz',None,'quiz','Quiz'),
],
13: [
 ('ask','yours','yours','The middle is yours'),
 ('ask','json','json','A reading with its name on it'),
 ('tick','deploy','deploy','The script is live','Checkpoint &mdash; the script is live',
  'My sheet exists, I opened Apps Script <strong>from inside it</strong>, deployed it as a Web app (Execute as&nbsp;Me, Who has access&nbsp;Anyone), and saved the <code>/exec</code> address somewhere I can copy it from twice.'),
 ('typer',None,'config','Settings typed'),
 ('tick','run','run','Rows are arriving','Checkpoint &mdash; rows are arriving',
  'The Shell printed an IP address, and <strong>new rows are appearing in my sheet while I watch</strong>.'),
 ('tick','see','see','The dashboard is live','Checkpoint &mdash; the dashboard is live',
  'My dashboard is showing live readings from my own board &mdash; and when I close it and open it again, the earlier readings are still on the graph.'),
 ('tick','exercise','exercise','Exercise done','Checkpoint &mdash; exercise done',
  'One reading a minute, and a dashboard that opens on a whole school day.'),
 ('quiz',None,'quiz','Quiz'),
],
}
